In [1]:
from modules.tweet_data import read_raw_data
from modules.topics import TopicSeries, display_components

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
import spacy
import pickle
import datetime as dt

import matplotlib.pyplot as plt

In [2]:
tweet_df = read_raw_data()
es = pd.read_csv('data/ES.csv')
es = es[es.Time == '15:00'][['Date','Time','Close']]
es.Date = pd.to_datetime(es.Date +' ' +'15:45')
es.drop('Time',axis=1,inplace=True)
es.set_index('Date', inplace=True)


Reading data


In [3]:
date_range = es['2011-12-30':'2020-5-31'].index


In [ ]:
ts=TopicSeries()
ts.fit(tweet_df, date_range)
ts.save('topics' + '-' + str(date_range[0].date()) + '-' + str(date_range[-1].date()) + '.p')
    

In [ ]:
batches = [date_range[-500:], 
           date_range[-1000:-499], 
           date_range[-1500:-999], 
           date_range[:-1499]]

for batch in batches:
    ts=TopicSeries()
    ts.fit(tweet_df, batch)
    ts.save('data/topics' + '-' + str(batch[0].date()) + '-' + str(batch[-1].date()) + '.p')
    

In [10]:
ts = pickle.load(open('data/topics-2011-12-30-2020-05-29.p','rb'))

In [4]:
classi = pd.read_csv('data/handle_class.csv')
tweet_df = pd.merge(tweet_df,classi[['class','handle','subclass']],on=['handle'], right_index=True)
# Need to resort by index as merge messes up with datetime indexing
tweet_df.sort_index(inplace=True)
tweet_df = tweet_df[tweet_df['class'] == 'fintwit']

In [5]:
tweet_df.head()

tweet_id       handle  \
timestamp                                    
2006-09-22 09:02:46     33743         guan   
2006-09-22 09:21:33     33745         guan   
2007-01-17 21:43:23   3175083  MarketWatch   
2007-01-17 21:43:25   3175143  MarketWatch   
2007-01-17 21:44:50   3175323  MarketWatch   

                                                                 tweet  \
timestamp                                                                
2006-09-22 09:02:46                                      Hello, World!   
2006-09-22 09:21:33  Working on a cool new project at Steffen's house.   
2007-01-17 21:43:23  Ex-Cendant chairman gets 12-year-plus prison s...   
2007-01-17 21:43:25  Ex-Cendant chairman gets 12-year prison senten...   
2007-01-17 21:44:50  Home builders' sentiment rises to highest leve...   

                       class subclass  
timestamp                              
2006-09-22 09:02:46  fintwit  opinion  
2006-09-22 09:21:33  fintwit  opinion  
2007-01-17 21:43:23  fintwit     news  
2007-01-17 21:43:25  fintwit     news  
2007-01-17 21:44:50  fintwit     news

In [5]:
ts=TopicSeries()
ts.fit(tweet_df, date_range)
ts.save('data/topics-fintwit' + '-' + str(date_range[0].date()) + '-' + str(date_range[-1].date()) + '.p')

KeyboardInterrupt: 

In [8]:
nlp =spacy_twitter_model()

In [1]:
    def twitter_tokenizer(d,
                          model=nlp,
                          urls=True,
                          stop_words=True,
                          lowercase=True,
                          alpha_only=True,
                          hashtags=False,
                          lemma=False):
        """Full tokenizer with flags for processing steps
        urls: If True, remove URLs
        stop_words: If True, removes stop words
        lowercase: If True, lowercases all tokens
        alpha_only: If True, removes all non-alpha characters
        lemma: If True, lemmatizes words
        The tokenizer also removes all URLS
        """
        parsed = d
        # token collector
        tokens = []
        for t in parsed:
            # remove URLs
            if t.like_url or t._.is_piclink & urls:
                continue
            # only include stop words if stop words==True
            if t.is_stop & stop_words:
                continue
            # only include non-alpha is alpha_only==False
            if not t.is_alpha & alpha_only:
                if hashtags:
                    continue
                else:
                    if not t._.is_hashtag:
                        continue
            if lemma:
                t = t.lemma_
            else:
                t = t.text
            if lowercase:
                t = t.lower()
            tokens.append(t)
        return tokens

NameError: name 'nlp' is not defined

In [15]:
[twitter_tokenizer(text) for text in nlp.pipe(sub_df)]

[['Number',
  'UK',
  '#coronavirus',
  'cases',
  'rises',
  'Bulgaria',
  'reports',
  'death',
  'Ivory',
  'Coast',
  'confirms',
  'case',
  'FIFA',
  'Congress',
  'postponed',
  'Canada',
  'sets',
  'm',
  'fund',
  'fight',
  'outbreak',
  'Follow',
  'latest',
  '#COVID19'],
 ['#Algeria’s',
  'FM',
  'Accuses',
  'Foreign',
  'Parties',
  'Supporting',
  'Hirak',
  'Activists'],
 ['Nearly',
  'half',
  'Americans',
  'pay',
  'federal',
  'income',
  'taxes',
  'poor',
  'people',
  'pay',
  'portion',
  'income',
  'taxes',
  'rich',
  'people',
  'Payroll',
  'taxes',
  'sales',
  'taxes',
  'consumption',
  'taxes'],
 ['logic', 'stays', 'home', 'sending', 'checks'],
 ['German', 'YouTubers', 'rally', 'racism', '#coronavirus', 'spreads'],
 ['La', 'realidad', 'desacuerda'],
 [],
 ['divisive', 'politics', 'lighthearted', 'distraction', 'coronavirus'],
 ['goes', 'quick', 'trip', 'lows'],
 ['Emmmm'],
 ['best', 'got', 'far'],
 ['come',
  'rooms',
  'stuff',
  'agree',
  'means',


In [21]:
[' '.join(twitter_tokenizer(text)) for text in nlp.pipe(sub_df, disable=["tagger","parser", "ner"])]

['Number UK #coronavirus cases rises Bulgaria reports death Ivory Coast confirms case FIFA Congress postponed Canada sets m fund fight outbreak Follow latest #COVID19',
 '#Algeria’s FM Accuses Foreign Parties Supporting Hirak Activists',
 'Nearly half Americans pay federal income taxes poor people pay portion income taxes rich people Payroll taxes sales taxes consumption taxes',
 'logic stays home sending checks',
 'German YouTubers rally racism #coronavirus spreads',
 'La realidad desacuerda',
 '',
 'divisive politics lighthearted distraction coronavirus',
 'goes quick trip lows',
 'Emmmm',
 'best got far',
 'come rooms stuff agree means canceling summer school university administrators',
 'sounds good product needed dilute tbh',
 'understand job loss baked nice day',
 'Bond equity decoupling mean little Bonds overbought correlation sustainable',
 'pointing mid high level agencies positions DC stayed vacant election day answers phone #MAGA geniuses laugh need offices guess answers pho

In [17]:
nlp.pipeline

[('tagger', <spacy.pipeline.pipes.Tagger at 0x7efc4d0fced0>),
 ('parser', <spacy.pipeline.pipes.DependencyParser at 0x7efca49f1440>),
 ('ner', <spacy.pipeline.pipes.EntityRecognizer at 0x7efb14f76c90>)]

In [18]:
disable=["parser", "ner"]
list(nlp.pipe(sub_df, disable=["parser", "ner"]))

[- Number of UK #coronavirus cases rises to 456 - Bulgaria reports its first death - Ivory Coast confirms its first case - 70th FIFA Congress postponed  - Canada sets up $730m fund to fight the outbreak  Follow the latest on #COVID19 👉 https://aje.io/zcljp  pic.twitter.com/5n6XHRzGzu,
 #Algeria’s FM Accuses 'Foreign Parties' of Supporting Hirak Activists  https://aawsat.com/node/2174756 ,
 Nearly half of Americans don’t pay federal income taxes.  But poor people pay about the same portion of their income in taxes as rich people.  How? Payroll taxes, sales taxes, and consumption taxes. https://www.youtube.com/watch?v=kXCGbAv8YPw …,
 Using your logic that everyone stays home, what would sending checks do?,
 German YouTubers rally against racism as #coronavirus spreads  http://xhne.ws/Flo2N  pic.twitter.com/rK5iWsCc7j,
 La realidad desacuerda https://twitter.com/LANACION/status/1237538867768463363 …,
  https://www.amazon.com/Tariffs-Foster-Political-Dysfunction-2-Sided/dp/B07BDBZ55L/ref=m

In [9]:
display_components(ts.nmf_dict['2020-03-12'], ts.tfidf_dict['2020-03-12'].get_feature_names(),20)

Topic 0:
coronavirus pandemic new cases says outbreak positive health tested #coronavirus live world italy breaking hanks china declares tom house global
Topic 1:
good news point luck morning idea thread pretty thing night bad look finally lord advice job sign question guess looking
Topic 2:
trump travel europe president days ban says uk speech address virus european donald restrictions #coronavirus friday united nation eu suspends
Topic 3:
right people know going think time need day today sure thing virus want said long way markets week lot point
Topic 4:
market bear dow stock stocks futures trading close points today territory day bull markets high limit open wall street oil


In [10]:
display_components(ts.nmf_dict['2020-03-12'], ts.tfidf_dict['2020-03-12'].get_feature_names(),20)

Topic 0:
coronavirus pandemic new cases says outbreak positive health tested #coronavirus world live italy breaking hanks china declares tom house global
Topic 1:
good news point luck morning idea thread pretty thing night bad look finally lord advice sign job question guess policy
Topic 2:
trump travel europe president days ban says uk speech address virus european donald restrictions #coronavirus friday united nation eu suspends
Topic 3:
right people know going think time need day today sure thing virus want said long way markets week lot point
Topic 4:
market bear dow stock stocks futures trading close points today territory bull day markets high limit open wall street oil


In [3]:
top_display = 20
top_words = []
word_features =  ts.tfidf_dict['2018-10-19'].get_feature_names()
for topic_idx, topic in enumerate(ts.nmf_dict['2018-10-19'].components_):
    top_words_idx = topic.argsort()[::-1][:top_display]
    top_words.append([word_features[i] for i in top_words_idx])

In [4]:
ts.nmf_dict['2018-10-19'].reconstruction_err_

107.09420242775161

In [ ]:
Measures between topics and days:

Conclusion: cosine similarity between top words should work

Cross entropy could work for LDA if probabilities. Take top XX words from each topic, and calculate
cross entropy with next day. You need to concat the words and find the index for each word in each day

Are NMF vectors probabilities?

Topics  
NMF  
Calc:   
recon error  
topic coherence (intraday) if high average, probably less topics leading, if low, more topics  
between days distances  
Avg of max  If low, change in subjects  
num Of unique topics   If low, change in subjects

# Cosine Similarity

In [20]:
top_words[0]

['trump',
 'like',
 'saudi',
 'khashoggi',
 'people',
 'says',
 'think',
 'good',
 'time',
 'dead',
 'looks',
 'know',
 'jamal',
 'arabia',
 'president',
 'certainly',
 'going',
 'journalist',
 'way',
 'right']

In [21]:
nlp_mid = spacy.load('en_core_web_md')

In [19]:
cosine_similarity([nlp_mid(' '.join(top_words[i])).vector for i in range(len(top_words))])

array([[1.0000001 , 0.8195414 , 0.6415489 , 0.6218434 , 0.50415957],
       [0.8195414 , 0.9999999 , 0.5254425 , 0.54699445, 0.46578452],
       [0.6415489 , 0.5254425 , 0.99999964, 0.7501086 , 0.706774  ],
       [0.6218434 , 0.54699445, 0.7501086 , 1.0000002 , 0.64579254],
       [0.50415957, 0.46578452, 0.706774  , 0.64579254, 1.0000001 ]],
      dtype=float32)

In [22]:
batch

DatetimeIndex(['2020-05-18 15:45:00', '2020-05-19 15:45:00',
               '2020-05-20 15:45:00', '2020-05-21 15:45:00'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [29]:
dates = ['2020-05-19', '2020-05-20', '2020-05-21']

In [26]:
ts.nmf_dict

{'2020-05-19': NMF(n_components=5, random_state=42),
 '2020-05-20': NMF(n_components=5, random_state=42),
 '2020-05-21': NMF(n_components=5, random_state=42)}

In [30]:
top_words_list = []
top_args_list = []
top_display = 20

for date in dates:
    top_words = []
    top_args = []
    word_features =  ts.tfidf_dict[date].get_feature_names()
    for topic_idx, topic in enumerate(ts.nmf_dict[date].components_):
        top_words_idx = topic.argsort()[::-1][:top_display]
        top_words.append([word_features[i] for i in top_words_idx])
        top_args.append(top_words_idx)
    top_words_list.append(top_words)
    top_args_list.append(top_args)

In [32]:
concat_words = [[' '.join(top_words) for top_words in sub_top_list] for sub_top_list in top_words_list]
word_vectors = [[nlp_mid(topic_words).vector for topic_words in concat_word] for concat_word in concat_words]

In [50]:
topic_coherence = []
topic_coherence_diff = []
num_topics_change = []

n_topics = 5
den = (n_topics**2-n_topics)
for i in range(len(word_vectors)-1):
    cs = cosine_similarity(word_vectors[i] + word_vectors[i+1])
    # Topic coherence
    tc = (cs[0:n_topics,0:n_topics].sum() - cs[0:n_topics,0:n_topics].diagonal().sum())/den
    topic_coherence.append(tc)
    # Topic coherence difference betweent day i and i+1
    tcd = cs[0:n_topics,n_topics:2*n_topics].max(axis=1).mean()
    topic_coherence_diff.append(tcd) 
    num_ts = len(np.unique(cs[0:n_topics,n_topics:2*n_topics].argmax(axis=1)))
    num_topics_change.append(num_ts)
tc = (cs[n_topics:2*n_topics,n_topics:2*n_topics].sum() \
      - cs[n_topics:2*n_topics,n_topics:2*n_topics].diagonal().sum())/den
topic_coherence.append(tc)
  


# Entropy

In [51]:
top_args

[array([10657, 17005, 17100,  4928, 17145, 18839,  7623, 14520,  8009,
         3695, 12601,  7819, 11632, 16256,  9813,  2635, 18841, 16262,
        18438, 17276]),
 array([10193, 10364, 10359,  6946, 17560, 15870, 18838, 12601, 14520,
        14781,  1265,  9813, 15866,  9194,  8606, 10800, 10395,  1606,
         3417, 12006]),
 array([ 7836, 12932, 11640, 11298, 16964, 17106, 10437, 17025, 17005,
        17542,  9813, 11998,  6508,  9765, 12832, 15870,  2277, 16379,
         3436,  8191]),
 array([17458,  7196, 16604, 12330, 13224, 12331, 15178,  2832, 14921,
         4671, 10574, 11632,  2850,  1288,  2825,  4285,  2992, 11640,
         6903, 10526]),
 array([ 1664,  1606,  6004,  7846,  1573, 14442, 15297, 11131, 14830,
        18300, 14385,  6464,  7845,  3893, 16318,  9159, 10277,  8606,
        11133, 18860])]

In [56]:
# 5x20, each of these is a probability, how to use entropy to measure?
ts.nmf_dict[date].components_[:,top_args[0]]

array([[9.41691146e-01, 7.29245633e-01, 7.22425772e-01, 5.82367276e-01,
        5.40866538e-01, 4.67197163e-01, 4.54668552e-01, 4.54618090e-01,
        4.44260666e-01, 4.39739661e-01, 4.35161474e-01, 3.99852181e-01,
        3.91100571e-01, 3.79672436e-01, 3.39545932e-01, 3.29667052e-01,
        3.24333526e-01, 3.14946909e-01, 2.97518570e-01, 2.90099951e-01],
       [8.33436601e-03, 6.34034190e-04, 0.00000000e+00, 3.16908490e-02,
        3.24202594e-03, 0.00000000e+00, 0.00000000e+00, 6.08975172e-02,
        0.00000000e+00, 0.00000000e+00, 6.35425280e-02, 1.98853321e-02,
        0.00000000e+00, 0.00000000e+00, 4.76677619e-02, 1.03352506e-02,
        1.34543845e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.46384721e-02, 1.78969527e-02, 4.06346078e-02,
        0.00000000e+00, 0.00000000e+00, 2.94953183e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 8.17845204e-02, 0.0000

In [58]:
from scipy.stats import entropy

In [104]:
# Need to match word probabilities/indices between days
aaa = ts.nmf_dict[date].components_[0]/ts.nmf_dict[date].components_[0].sum()
bbb = ts.nmf_dict[date].components_[1]/ts.nmf_dict[date].components_[1].sum()

In [105]:
aaa[aaa>0].dot(np.log(bbb[bbb>0]))

ValueError: shapes (17844,) and (5872,) not aligned: 17844 (dim 0) != 5872 (dim 0)

In [119]:
A = ts.nmf_dict[date].components_
A[A==0] = 1e-15
A

array([[1.03869419e-02, 3.19901698e-02, 5.92124026e-04, ...,
        1.72551758e-04, 3.35822443e-04, 1.72551758e-04],
       [1.00000000e-15, 1.00000000e-15, 1.00000000e-15, ...,
        1.00000000e-15, 1.00000000e-15, 1.00000000e-15],
       [7.67170612e-03, 1.00000000e-15, 1.00000000e-15, ...,
        1.00000000e-15, 1.00000000e-15, 1.00000000e-15],
       [1.02803427e-03, 2.37004812e-02, 1.00000000e-15, ...,
        5.28806240e-05, 1.00000000e-15, 5.28806240e-05],
       [1.00000000e-15, 1.00000000e-15, 1.40111904e-04, ...,
        1.00000000e-15, 1.00000000e-15, 1.00000000e-15]])

In [123]:
entropy(ts.nmf_dict[date].components_[0])

8.375995828555052

In [125]:
entropy(ts.nmf_dict[date].components_[0],qk=(ts.nmf_dict[date].components_[1]))

17.086682064097044

In [132]:
[[entropy(ts.nmf_dict[dates[0]].components_[i],qk=(ts.nmf_dict[dates[0]].components_[j])) for i in range(5)]for j in range(5)]

[[0.0, inf, inf, inf, inf],
 [inf, 0.0, inf, inf, inf],
 [inf, inf, 0.0, inf, inf],
 [inf, inf, inf, 0.0, inf],
 [inf, inf, inf, inf, 0.0]]

In [ ]:
[[entropy(ts.nmf_dict[date].components_[i],qk=(ts.nmf_dict[date].components_[j])) for i in range(5)]for j in range(5)]

In [113]:
entropy(ts.nmf_dict[date].components_[0],qk=(ts.nmf_dict[date].components_[2]+1e-15))

18.70549419755346

In [114]:
entropy(ts.nmf_dict[date].components_[0],qk=(ts.nmf_dict[date].components_[3]+1e-15))

15.274803048704879

In [115]:
entropy(ts.nmf_dict[date].components_[0],qk=(ts.nmf_dict[date].components_[4]+1e-15))

19.802016016333614

In [88]:
ts.nmf_dict[date].components_[0].dot(np.log(ts.nmf_dict[date].components_[0]))

/Users/lalopey/opt/anaconda3/envs/tweet-sentiment/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


nan

In [98]:
ts.nmf_dict[date].components_[1].sum()

14.961622403118877

In [89]:
ts.nmf_dict[date].components_[0][ts.nmf_dict[date].components_[0] > 0.01].dot(np.log(ts.nmf_dict[date].components_[0][ts.nmf_dict[date].components_[0] > 0.01]))

-228.81431983349367

In [80]:
ts.nmf_dict[date].components_[0] * np.log(ts.nmf_dict[date].components_[0])

/Users/lalopey/opt/anaconda3/envs/tweet-sentiment/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/Users/lalopey/opt/anaconda3/envs/tweet-sentiment/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


array([-0.0474393 , -0.11012061, -0.00440054, ..., -0.00149513,
       -0.00268622, -0.00149513])

In [134]:
q = [1]
if q:
    print(1)

1
